export const Users = [
    {
        id: 1,
        profilePic: "person/1.jpeg",
        username: "Safak Kocaoglu",
    },
    {
        id: 2,
        profilePic: "person/2.jpeg",
        username: "Frak Kocaoglu",
    },
    {
        id: 3,
        profilePic: "person/3.jpeg",
        username: "Facky Kocaoglu",
    },
    {
        id: 4,
        profilePic: "person/4.jpeg",
        username: "Lucky Kocaoglu",
    },
    {
        id: 5,
        profilePic: "person/4.jpeg",
        username: "Naidu Kocaoglu",
    },
    {
        id: 6,
        profilePic: "person/6.jpeg",
        username: "Lomba Kocaoglu",
    },
    {
        id: 7,
        profilePic: "person/7.jpeg",
        username: "Sofada Kocaoglu",
    },
    {
        id: 8,
        profilePic: "person/8.jpeg",
        username: "Sanky Kocaoglu",
    },
    {
        id: 9,
        profilePic: "person/9.jpeg",
        username: "Safak Kocaoglu",
    },
    {
        id: 10,
        profilePic: "person/10.jpeg",
        username: "Dancy Kocaoglu",
    },
]

export const Posts = [
    {
        id: 1,
        desc: "Love for all, hatred for none.",
        photo: "post/1.jpeg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        desc: "Love for all, hatred for none.",
        photo: "post/2.jpeg",
        date: "5 mins ago",
        userId: 2,
        like: 323,
        comment: 9,
    },
    {
        id: 3,
        desc: "Love for all, hatred for none.",
        photo: "post/3.jpeg",
        date: "5 mins ago",
        userId: 3,
        like: 3,
        comment: 9,
    },
    {
        id: 4,
        desc: "Love for all, hatred for none.",
        photo: "post/4.jpeg",
        date: "5 mins ago",
        userId: 4,
        like: 2,
        comment: 9,
    },
    {
        id: 5,
        desc: "Love for all, hatred for none.",
        photo: "post/5.jpeg",
        date: "5 mins ago",
        userId: 5,
        like: 322,
        comment: 91,
    },
    {
        id: 6,
        desc: "Love for all, hatred for none.",
        photo: "post/6.jpeg",
        date: "5 mins ago",
        userId: 6,
        like: 132,
        comment: 19,
    },
    {
        id: 7,
        desc: "Love for all, hatred for none.",
        photo: "post/7.jpeg",
        date: "5 mins ago",
        userId: 7,
        like: 321,
        comment: 91,
    },
    {
        id: 8,
        desc: "Love for all, hatred for none.",
        photo: "post/8.jpeg",
        date: "5 mins ago",
        userId: 8,
        like: 24,
        comment: 22,
    },
    {
        id: 9,
        desc: "Love for all, hatred for none.",
        photo: "post/9.jpeg",
        date: "5 mins ago",
        userId: 9,
        like: 312,
        comment: 79,
    },
    {
        id: 10,
        desc: "Love for all, hatred for none.",
        photo: "post/10.jpeg",
        date: "5 mins ago",
        userId: 10,
        like: 302,
        comment: 89,
    },
]